In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


- 2 Dimemsional array

In [6]:
import numpy as np
arr=np.array([[1,2,6],[3,4,5]])
print(arr)

[[1 2 6]
 [3 4 5]]


In [62]:
import numpy as np

a=np.array(10) 
b=np.array([1,2,3,4]) #1D ARRAY
c=np.array([[1,2,3],[4,5,6]]) #2D ARRAY
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3D ARRAY

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



0
1
2
3


array(10)

In [13]:
import numpy as np

a=np.array([1,2,3] ,ndmin=5) #5D ARRAY
print(a)

[[[[[1 2 3]]]]]


In [15]:
import numpy as np

a=np.array([1,2,3,4])

print(a[2]+a[3])

7


In [12]:
import numpy as np

a=np.array([1,2,3,4],dtype='S') # changed the datatype to String  Note: Cannot the change the string array to integer
print(a)
b=a.astype('i') # created a new b by changing the datatype of the array b
print(a.dtype)
print(b)
print(b.dtype)

[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32


- shape

In [23]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(x.shape)

(3, 3)


- reshape

In [29]:
x=np.array([[1,2,3,4,5,6,7,8,9]]) 
print(x.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
a=np.array([[1,2,3],[4,5,6]])
for x in a:
    print(x)

[1 2 3]
[4 5 6]


- Concatenation

In [33]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


- stack

In [34]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack((a,b),axis=1)
print(c)

[[1 4]
 [2 5]
 [3 6]]


- Horizontal Stack

In [36]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


- Vertical stack

In [37]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


- depth wise stack

In [40]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.dstack((a,b))
print(c)

[[[1 4]
  [2 5]
  [3 6]]]


- append

In [41]:
a=np.array([[1,2,3],[4,5,6]])
b=np.append(a,[7,8,9])
print(b)

[1 2 3 4 5 6 7 8 9]


- appending two arrays

In [43]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.append(a,b)
print(c)

[1 2 3 4 5 6]


- copy()

In [8]:
import numpy as np
a=np.array([1,2,3])
b=a.copy()
a[0]=10
print(a)
print(b)

[10  2  3]
[1 2 3]


- view()

In [9]:
import numpy as np
a=np.array([1,2,3])
b=a.view()
a[0]=10
print(a)
print(b)

[10  2  3]
[10  2  3]


In [15]:
x=np.array([1,2,3,4,5,6]) 
a=np.array_split(x,3)
print(a)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [21]:
x=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]) 
a=np.hsplit(x,3)
print(a)

[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]


In [27]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]]) 
a=np.vsplit(x,3)
print(a)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [30]:
x=np.array([1,2,3,4,5,6]) 
a=np.searchsorted(x,4.5)
print(x)

[1 2 3 4 5 6]


-sort

In [32]:
x=np.array(['a','c','f','b','d','e']) 
a=np.sort(x)
print(a)

['a' 'b' 'c' 'd' 'e' 'f']


In [39]:
np.arange(1,20,2)


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
r=np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [58]:
a=np.arange(1,21)   
b=a ** 2
b.resize(4,5)
b


array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400]])

In [100]:
a=np.zeros((8,8))
a[1::2]=1
a


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [103]:
a=np.eye(2,k=1)
b=np.eye(2,k=-1)
print(b)
a

[[0. 0.]
 [1. 0.]]


array([[0., 1.],
       [0., 0.]])

-Bernoulli Distribution
-Uniform Distribution
-Binomial Distribution
-Normal Distribution
    -empirical rule

- seed()

In [5]:
a=np.random.rand()
print(a)

0.8378805708954914


In [24]:
import numpy as np
a=np.random.rand(1,20,30)
print(a)

[[[8.22564439e-01 1.13680184e-01 6.99614817e-02 9.68734565e-01
   9.54753093e-01 7.06783272e-01 6.43162501e-01 5.75319078e-02
   4.27885360e-01 1.01942895e-01 3.01180446e-01 6.75953179e-01
   4.81170358e-01 5.53567302e-01 3.23453121e-01 3.47930287e-01
   2.40474602e-01 7.10360958e-01 5.37796736e-01 4.43247501e-01
   6.59290816e-01 5.88933100e-01 4.75182064e-01 9.90279813e-01
   6.34708809e-01 2.85721780e-01 7.55352183e-01 9.11568246e-03
   1.77832592e-01 2.82791820e-01]
  [4.32277158e-01 9.67308034e-01 3.30705777e-01 9.09260675e-01
   2.53508106e-01 7.24481223e-01 5.10019238e-01 1.53881165e-01
   2.93731561e-03 3.53347169e-01 2.37397742e-01 6.83298582e-01
   9.08813104e-01 6.80522598e-01 8.00789169e-01 1.32871867e-02
   9.69232346e-01 6.69541149e-01 8.65750231e-01 3.92871231e-01
   4.40906718e-01 6.15794596e-02 3.52844190e-01 8.11376573e-01
   7.55236233e-01 2.20069197e-01 7.77096541e-01 8.95552467e-01
   7.30904441e-01 8.51601464e-01]
  [5.81973124e-01 8.81613349e-01 5.94664507e-01 3.

In [26]:
a=np.random.randint(low=1,high=8,size=10)
a

array([2, 7, 1, 3, 2, 2, 1, 2, 3, 5])

In [127]:
a=np.random.randn(1,3,3)
a

array([[[ 0.74261106,  1.3403928 ,  0.17775783],
        [ 2.27017517,  0.00766142,  0.66176341],
        [-0.0196208 ,  0.23043243,  0.42585472]]])

In [46]:
a=np.arange(10,50)
a


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [31]:
r=np.arange(9)
r.resize(3,3)
r

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
a=np.zeros(10)
a[5]=1
print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


- Celsius to Fahrenheit 

In [93]:
a=np.array(int(input("Enter Celsius degree")))
b=np.array(a*(9/5)+32)
print(b)

53.6


- Fahrenheit  to Celsius

In [94]:
a=np.array(int(input("Enter Fahrenheit degree")))
b=np.array((a-32)*5/9)
print(b)

-11.11111111111111


- Normal
 [random.normal()]

In [97]:
a=np.random.normal()
a

0.4187183108890532

- scale
    - get the standard deviation of random values

In [107]:
a=np.random.normal(scale=4.0)
a

-5.711390805302602

- loc
    - mean

In [96]:
a=np.random.normal(loc=2)
a

0.997528087599242

- size

In [112]:
a=np.random.normal(size=4)
a

array([-0.64618518, -0.89271058, -1.31964742,  0.52590411])

In [113]:
a=np.random.normal(loc=2,scale=5,size=4)
a

array([1.50899462, 3.9584296 , 0.45141127, 1.65709111])

-UNIFORM
    [random.uniform]

In [119]:
a=np.random.uniform(low=3,high=5,size=(100))
a

array([3.25981468, 3.37991995, 3.49072926, 4.58124921, 3.16019118,
       3.75320291, 3.05698694, 4.05208832, 3.14607493, 4.16637583,
       4.11101824, 3.30228697, 3.16053038, 4.97336997, 4.81443939,
       3.39785143, 4.413643  , 4.29017929, 3.89852976, 3.73600175,
       4.93412785, 3.34737036, 4.2206723 , 4.71716236, 4.24847503,
       4.53647882, 3.1504633 , 4.87431273, 4.88553196, 4.59672358,
       4.44387343, 4.24450847, 3.09826707, 3.71756234, 4.82153467,
       4.51772534, 4.82750531, 3.84215996, 3.33972237, 3.90521325,
       3.42275442, 3.40740738, 4.53213857, 3.77826389, 4.30302227,
       3.10636821, 3.23305579, 3.93033764, 4.71719189, 3.0487569 ,
       3.57881632, 4.78855574, 3.71400208, 4.64043345, 3.95859983,
       4.61084939, 3.0632613 , 3.56065037, 3.00305773, 3.2757311 ,
       4.85735404, 4.20203968, 4.18544639, 3.16107178, 4.41166665,
       3.2731347 , 4.21106142, 4.03878346, 3.11154616, 3.42265608,
       3.41604016, 3.28604912, 3.91035419, 4.10123193, 3.84350

- Numpy program to multiply an array of dimension (2,2,3) by an array with dimesion (2,2)

In [74]:
import numpy as np
a=np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
a.reshape(2,2,3)
# print(a)
b=np.array([[1, 2],[3, 4]])
# print(b)
# print(a*b[:,:,])
print(a*b.reshape(2,2,1))
# b.reshape(1, 1, -1)



[[[ 1  2  3]
  [ 8 10 12]]

 [[21 24 27]
  [40 44 48]]]


2

- Numpy program to convert a list of numeric values into one dimesional numpy array

In [15]:
a=[1,2,3,4]
np.array(a,ndmin=1)

array([1, 2, 3, 4])

In [53]:
a=4
b=2
b//a

0

# Basic Mathematical Operations of NumPy array

In [87]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)

[ 6  8 10 12]


In [61]:
print(b-a)

[4 4 4 4]


In [64]:
print(a*b)

[ 5 12 21 32]


[**]
power

In [66]:
a**b 

array([    1,    64,  2187, 65536])

[//]
floor division

In [84]:
b//a

array([5, 3, 2, 2])

In [89]:
print(a.min())
print(b.max())

1
8


In [83]:
print(a.sum())
b.sum()

10


26

[cumsum()]
cumulative sum

In [85]:
a=np.array([1,2,3,4])
a.cumsum()

array([ 1,  3,  6, 10])

[cumprod()]
cumulative product

In [86]:
a=np.array([1,2,3,4])
a.cumprod()

array([ 1,  2,  6, 24])

In [93]:
import numpy as np
a=np.array([[1, 23,45],[33, 41,98],[55,63,86]])
np.diff(a)

array([[22, 22],
       [ 8, 57],
       [ 8, 23]])

- square root

In [94]:
np.sqrt(a)

array([[1.        , 4.79583152, 6.70820393],
       [5.74456265, 6.40312424, 9.89949494],
       [7.41619849, 7.93725393, 9.2736185 ]])

- square

In [95]:
np.square(a)

array([[   1,  529, 2025],
       [1089, 1681, 9604],
       [3025, 3969, 7396]])

In [102]:
x=np.array([[1,2,3,4],[5,6,7,8]])
s=np.sum(x)
p=np.prod(x)
d=np.diff(x)
print("Sum of the Array is ",s)
print("Product of the Array is ",p)
print("Difference of the Array is ",d)


Sum of the Array is  36
Product of the Array is  40320
Difference of the Array is  [[1 1 1]
 [1 1 1]]


itemsize- 

In [119]:
x=np.array([1,2,3,4],dtype=np.float16)
x.itemsize

2

nbytes= Total bytes consumed by the elements in an array

In [122]:
x=np.zeros((3,5,2),dtype=np.complex128)
x.nbytes

480